name: Publish Docker image to GHCR

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set lowercase image tags
        id: meta
        run: |
          REPO_LC=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          SHA_TAG=${GITHUB_SHA::7}
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            echo "tags=ghcr.io/${REPO_LC}:${GITHUB_REF_NAME},ghcr.io/${REPO_LC}:latest" >> $GITHUB_OUTPUT
          else
            echo "tags=ghcr.io/${REPO_LC}:${SHA_TAG}" >> $GITHUB_OUTPUT
          fi

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}
