# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - level1task

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: levelprodacr.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_98D3DCC86AF146518B2B45F3A64F3688 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_A9801317878244C5B9E991679384508A }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: levelprodacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_98D3DCC86AF146518B2B45F3A64F3688 }}/levelprodacr/levelprodacr/levelprodacr/level-api:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D2E2818CCE7949F88E9E20110DF767AD }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_72D797DD07364DF6B0FC4B8192157B89 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_73AE4162231E438992D238B6D0988EAD }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'level1task'
          slot-name: 'Production'
          images: 'levelprodacr.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_98D3DCC86AF146518B2B45F3A64F3688 }}/levelprodacr/levelprodacr/levelprodacr/level-api:${{ github.sha }}'
          